### ISSUE TITLE
umbrella issue for bugs.

### ISSUE THREAD

**Issue by n8tb1t** [catalystdevelopment/catalyst-gui-wallet#1]
In this umbrella issue, we'd like to provide a means for others to share any issues encountered regarding the work-in-progress wallet functionality.

- [ ] fix README.md.
- [x] add remote nodes list repo.
- [ ] set node fee to 10cx ...?
- [x] find someone with access to macOS for mac builds.
- [x] improve design.
- [x] change font.
- [x] linux testing
- [x] windows testing
- [ ] add dirtybits wallet for donations.

**Comment by dirtybits** [comment]
Heyo, here's my donation wallet:
cat1Az2Xwt4byGrYeiKwxacV2pMahz7JaFPqW7eLbFPDP9kKT4rYMMq428KsZMbv8xK44j3dKBvaZW1VGzX4WVvb4R8ndN6WnD
